Refactor of API class into UrlResolver and Utilities classes
internetarchive/internetarchivebot pull request #14
Opened 2021-02-04 01:44 UTC by harej

This pull request:
* Refactors URL resolving methods (i.e., "is this link a Wayback Machine link") into a new class called UrlResolver
* Creates a new Utilities class that currently only has two methods and will have more added soon
* Fixes the current acceptance testing and writes new unit testing for UrlResolver methods

2021-03-27 16:23 UTC, cyberpower678 requested changes
The CURL handles will not initialize the way they are coded right now.  This will result in a fatal runtime error most likely.

I'm wondering why many test cases are commented out, and one of the acceptance result looks off.

2021-03-27 16:23 UTC, cyberpower678 commented on app/src/Core/APII.php
> +		} elseif ( self::hostMatch( $parts['host'], [ "archive.org", "waybackmachine.org" ] ) ) {
It should be web.archive.org.  Anything outside of it is not the Wayback Machine, and may be misinterpreted.  Try to be as specific as possible when it comes to domains.

2021-03-27 16:23 UTC, cyberpower678 commented on app/src/Core/APII.php
> +		} elseif ( self::hostMatch( $parts['host'], [ "archive.org", "waybackmachine.org" ] ) ) {
I note the old code didn't have it either, which is actually a bug. :p

2021-04-03 06:35 UTC, decodedfile commented
Duplicate of #

2021-07-18 04:32 UTC, closed without merging